### PR TITLE
Loadgen runner

### PR DESCRIPTION
**Pull request by mhofman**
# Summary

This (large) PR introduces a runner capable of orchestrating a chain node, a client ag-solo and the existing loadgen script, as well as several wrapper scripts to automate running the loadgen using any SDK revision, in the expected environment.

It's the base for running a daily loadgen on the latest agoric-sdk to capture historical performance data. See https://github.com/Agoric/agoric-sdk/issues/2630

The orchestrator starts a local chain node (or monitor node in the case of an remote chain), pipes and parses the slog using a FIFO file, and monitors events from the slog. At regular interval, it captures process information for the CPU usage of the chain process and its vat subprocesses, as well as the disk storage used by the chain. It can run multiple cycles of chain, client and loadgen, compressing and saving the chain storage and raw slog for every stage.

# Runner structure

The runner is setup as a node workspace package. Unlike the `loadgen` package, it doesn't depend on agoric-sdk. Since it tries to follow code patterns, it runs under SES using its own `install-ses` and uses a fork of `promise-kit`, mainly to avoid breaking changes such as RESM->NESM.

The runner is a CLI application composed of a `main.js` file parsing the command line and implementing the bulk of the orchestration logic. It relies on `tasks` that implement the specifics of setting up and running a chain node, running a local solo client, and running the load generator itself, all spawned as sub processes. Currently it supports running these tasks for a local chain, or against an external `stage` and `testnet` chain. The implementation uses a bunch of potentially reusable async, stream, process and filesystem helpers (currently not covered by any unit tests).

The output of all spawned sub processes is combined and prefixed into the stdout of the runner.

### CODE REVIEW

**Review by warner — APPROVED** [review]
Yay!

**Comment by mhofman** [comment]
@warner let me know if the readme and PR description make sense.

**Review by warner — APPROVED** [review]
Yeah, that looks good.. it might be good to have an extra paragraph or two near the top as a "welcome testnet validators!" instruction guide, to distinguish between using this repo for dailyperf purposes and using it to complete the run-a-loadgen task that we've asked them to do.

**Comment by mhofman** [comment]
I'm gonna fast follow up with another PR that fixes the AMM task and moves the readme, replacing it with something more appropriate.

**Pull request merged**
